version: "3.9"

services:
  task_tracker_api:
    build: .
    container_name: task_tracker_api
    restart: always
    ports:
      - "8050:8050"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
    volumes:
      - .:/app

    # Fix DNS resolution for Render Postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1
